# Generated by Django 5.2.8 on 2025-11-11 12:40

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('رمان ایرانی و خارجی', 'رمان ایرانی و خارجی'), ('داستان کوتاه', 'داستان کوتاه'), ('شعر', 'شعر'), ('تاریخی', 'تاریخی'), ('فلسفی', 'فلسفی'), ('روانشناسی', 'روانشناسی'), ('خودیاری و توسعه فردی', 'خودیاری و توسعه فردی'), ('علمی (علوم پایه، تکنولوژی)', 'علمی (علوم پایه، تکنولوژی)'), ('تاریخ ادبیات', 'تاریخ ادبیات'), ('تاریخ معاصر', 'تاریخ معاصر'), ('علوم (پزشکی، مهندسی، حقوق و ...)', 'علوم (پزشکی، مهندسی، حقوق و ...)'), ('هنر (سینما، موسیقی، نقاشی)', 'هنر (سینما، موسیقی، نقاشی)'), ('داستان\u200cهای مصور', 'داستان\u200cهای مصور'), ('کتاب\u200cهای آموزشی', 'کتاب\u200cهای آموزشی'), ('کتاب\u200cهای علمی تخیلی و فانتزی', 'کتاب\u200cهای علمی تخیلی و فانتزی'), ('کتاب\u200cهای مذهبی و دینی', 'کتاب\u200cهای مذهبی و دینی'), ('کتاب\u200cهای آشپزی و خانه\u200cداری', 'کتاب\u200cهای آشپزی و خانه\u200cداری'), ('کتاب\u200cهای سفر و جهانگردی', 'کتاب\u200cهای سفر و جهانگردی'), ('کتاب\u200cهای مرجع (دیکشنری، دانشنامه)', 'کتاب\u200cهای مرجع (دیکشنری، دانشنامه)'), ('سایر', 'سایر')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('street_detail', models.CharField(max_length=255)),
                ('date_of_year', models.DateField()),
                ('city', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='province', chained_model_field='province', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.city')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.province')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='main.province'),
        ),
        migrations.CreateModel(
            name='RequiredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_required', models.PositiveIntegerField(default=1)),
                ('given_number', models.PositiveIntegerField(default=0)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_items', to='main.book')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_items', to='main.library')),
            ],
        ),
    ]
