# Generated by Django 5.2.8 on 2025-11-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requireditem',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
